name: Update NASA APOD

on:
  schedule:
    - cron: '0 1 * * *'  # setiap jam 01:00 UTC
  workflow_dispatch:

jobs:
  update-apod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download APOD
        run: |
          curl "https://api.nasa.gov/planetary/apod?api_key=${{ secrets.NASA_API_KEY }}&hd=true" \
               | jq -r '.hdurl' \
               | xargs curl -o img/apod.jpg
      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add img/apod.jpg
          git commit -m "chore: update NASA APOD image" || echo "No changes"
          git push
